name: AQI Project Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *" # Every hour
  workflow_dispatch: # For manual triggering

jobs:
  run-airflow-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install apache-airflow
          pip install feast
          pip install -r airflow/dags/scripts/requirements.txt

      - name: Run Airflow DAG
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow
          airflow db init
          airflow dags trigger pipeline_dag

  train-and-save-model:
    runs-on: ubuntu-latest
    needs: run-airflow-pipeline
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: pip install feast scikit-learn pandas

      - name: Train and Save Model
        run: python airflow/dags/scripts/train_model.py

      - name: Push Model to Repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add airflow/project_output/
          git commit -m "Updated model"
          git push
