name: AQI Project Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *" # Every hour
  workflow_dispatch: # For manual triggering

jobs:
  run-airflow-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Intsall grpcio and googleapis
        run: |
          pip install grpcio
          pip install googleapis-common-protos

      - name: Install Dependencies
        run: |
          pip install apache-airflow
          pip install feast
          pip install -r dags/scripts/requirements.txt

      - name: Run Airflow DAG
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow
          airflow db init
          airflow dags trigger feature_and_training_pipeline

