name: AQI Project Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *" # Every hour
  workflow_dispatch: # For manual triggering

jobs:
  run-airflow-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Intsall grpcio and googleapis
        run: |
          pip install grpcio
          pip install googleapis-common-protos

      - name: Install Dependencies
        run: |
          pip install apache-airflow
          pip install feast==0.42.0
          pip install -r dags/scripts/requirements.txt

      - name: Initialize Airflow Database
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow
          airflow db migrate

      - name: Verify Airflow Installation
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow
          airflow version
      
      - name: Verify DAG Presence
        run: |
          ls -l $(pwd)/dags
      
  
      
      - name: Verify Directory Structure
        run: |
          echo "Current Working Directory: $(pwd)"
          ls -R $(pwd)
          ls -R $(pwd)/dags

      - name: List environment variables
        run: |
          printenv

      - name: List DAG import errors
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow
          export AIRFLOW__CORE__DAGS_FOLDER=$(pwd)/dags
          airflow dags list-import-errors

      - name: List DAGs
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow
          dagpath=$(pwd)/dags
          airflow dags list
      
      - name: Run Airflow DAG
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow
          export AIRFLOW__CORE__DAGS_FOLDER=$(pwd)/dags
          dagpath=$(pwd)/dags
          airflow dags trigger feature_and_training_pipeline

